### ISSUE TITLE
How to reconstruct ANNG?

### ISSUE THREAD

**Issue by nyapicom** [lerouxrgd/ngt-rs#3]
I guess `ngt::optim::refine_anng` is the one, but I don't know how to use it...
I tried to put `ngt::optim::AnngRefineParams::default()` into the second argument but the system crushed.

**Comment by lerouxrgd** [comment]
There is a unit test that uses it:

https://github.com/lerouxrgd/ngt-rs/blob/4dd6fdf1fb15f2fd4a29a952e2b54b81d3146fe8/src/optim.rs#L348-L369

You need to build the index beforehand. Does it help ? Otherwise can you make an example to reproduce the crash ?

Note that you cannot use `shared_mem` feature with `refine_anng` but the function should not be available if you use this feature.

**Comment by lerouxrgd** [comment]
> How to reconstruct ANNG

Do you mean [ANNG to reconstruct ONNG](https://github.com/yahoojapan/NGT/wiki/Optimization-Examples-Using-Python#anng-to-reconstruct-onng) ?

In this case, the function to use is [convert_anng_to_onng](https://docs.rs/ngt/0.4.1/ngt/optim/fn.convert_anng_to_onng.html). Note that you need to optimize the index in a very specific way, as described in the NGT documentation.

**Comment by nyapicom** [comment]
it worked well.
Thank you for your help.
